### ISSUE TITLE
GNG graph do not visualize

### ISSUE THREAD

**Issue by watashiwa-toki** [rcannood/GNG#1]
I try to plot GNG graph:
data(iris)
iris2 <- as.matrix(iris[,1:4])
a <- gng(iris2, max_iter = 20000, epsilon_b = 0.05, epsilon_n = 0.001, age_max = 200, max_nodes = 30, lambda = 200, alpha = 0.5, beta = 0.99, assign_cluster = T, verbose = T, make_logs = F, cpp = T)
flowsomlike_plot(a, iris[,5], max.size = 0.075)
NULL

flowsomlike_plot(gng_fit = a, labels = iris[,5], max.size = 0.075)
NULL

How to vizualize it?

**Comment by rcannood** [comment]
Hello Toki!

Thanks for trying out this very undocumented GNG package. The plotting function was indeed not working adequately, sorry for this. I've just pushed a new version of the package where it does work. Could you try reinstalling the package and trying it again? Let me know whether you like it :)

Kind regards,
Robrecht

**Comment by watashiwa-toki** [comment]
Reinstall the package, still dont work:

library(GNG)
data(iris)
iris2 <- as.matrix(iris[,1:4])
a <- gng(iris2, max_iter = 20000, epsilon_b = 0.05, epsilon_n = 0.001, age_max = 200, max_nodes = 30, lambda = 200, alpha = 0.5, beta = 0.99, assign_cluster = T, verbose = T, make_logs = F, cpp = T)
flowsomlike_plot(a, iris[,5], max.size = 0.075)
Error in mutate_impl(.data, dots) : 
  Evaluation error: object 'max_size' not found.
max_size = .075
flowsomlike_plot(a, iris[,5], max.size = 0.075)
Error in aes(x = i.X, xend = j.X, y = i.Y, yend = j.Y) : 
  could not find function "aes"
flowsomlike_plot(gng_fit = a, labels = iris[,5], max.size = 0.075)
Error in aes(x = i.X, xend = j.X, y = i.Y, yend = j.Y) : 
  could not find function "aes"

Maybe i doing wrong something?..

**Comment by rcannood** [comment]
My bad; could you try again?

**Comment by watashiwa-toki** [comment]
> flowsomlike_plot(a, iris[,5], max.size = 0.075)
Error in aes(x = i.X, xend = j.X, y = i.Y, yend = j.Y) : 
  could not find function "aes"
> flowsomlike_plot(gng_fit = a, labels = iris[,5], max.size = 0.075)
Error in aes(x = i.X, xend = j.X, y = i.Y, yend = j.Y) : 
  could not find function "aes"

**Comment by rcannood** [comment]
Just to make sure, did you reinstall GNG after the previous comment? I currently can't replicate your error:
``` R
Restarting R session...
> library(GNG)
> data(iris)
> iris2 <- as.matrix(iris[,1:4])
> a <- gng(iris2, max_iter = 20000, epsilon_b = 0.05, epsilon_n = 0.001, age_max = 200, max_nodes = 30, lambda = 200, alpha = 0.5, beta = 0.99, assign_cluster = T, verbose = T, make_logs = F, cpp = T)
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> flowsomlike_plot(a, iris[,5], max.size = 0.075)
```

![rplot](https://user-images.githubusercontent.com/553642/41192149-1e8ea10c-6bfa-11e8-9931-106f7af19ea2.png)

I've just enabled automated testing using [travis](https://travis-ci.org/rcannood/GNG/builds/390115336) to see if I can replicate your error there, but it'll take a few minutes to build all the dependencies.

**Comment by watashiwa-toki** [comment]
Now work fine, thanks!
![rplot](https://user-images.githubusercontent.com/33194329/41192144-e94e11b0-6c23-11e8-9861-c921dc3d647b.png)
I have a questions:
This is original GNG algorithm by Fritzke, without optimisations like in this paper https://www.sciencedirect.com/science/article/pii/S0925231212008351 ?

How flowsomlike_plot visualize multidimension GNG graph in 2D?

**Comment by rcannood** [comment]
It's based primarily on the algorithm as described by Fritzke, but I've
been wanting to add optimisations for a while now. I'll have a look at the
manuscript you provided!

The 2D visualisation is similar to the one provided by FlowSOM (
http://bioconductor.org/packages/release/bioc/html/FlowSOM.html, hence the
name), and uses Kamada Kawai to visualise the GNG. The inside circle
represents what percentages of groups are within that node, whereas the
outer bars represent the average value of each of the features provided. I
realise a legend is missing, I'll add one next week.

Does this answer your questions?

Robrecht

**Comment by watashiwa-toki** [comment]
Yes, thank you very much for valuable help!
